version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/gemfiles/rails_50"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/gemfiles/rails_51"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
